### ISSUE TITLE
Can we use docker exec

### ISSUE THREAD

**Issue by nnn-gif** [michielbdejong/snickers-proxy#35]
instead of using  docker-enter test.com

we can use docker exec,

**Comment by pierreozoux** [comment]
Be careful thought, I'm not sure `docker exec` sets up ENV variable.

**Comment by michielbdejong** [comment]
`docker-enter` is only for debugging, you can see if the mysql server is stopped, or do `tail -f /var/log/apache/error.log` to see where 500 internal server errors are coming from.
It is not used by snickers-proxy itself (exec is used there, for instance to do a mysqldump)

**Comment by pierreozoux** [comment]
`docker exec` can be used to start an interactive shell. (If you go to [docker exec page](https://github.com/jpetazzo/nsenter), they actually recommend using it :) )

**Comment by michielbdejong** [comment]
Ah ok that's good to know. Yes, then we should update the install instructions and remove the recommendation to install docker-enter.
